### ISSUE TITLE
Use hash of dAPI name when deriving sponsor wallet

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#145]
See: https://github.com/api3dao/airseeker-v2/pull/142#issuecomment-1833442938 also edit this in spec.

**Comment by bbenligiray** [comment]
Will https://github.com/api3dao/airseeker-v2/pull/142 need to be reverted?

**Comment by Siegrift** [comment]
Mhh, why?

I was thinking about updating the test and verifying that the sponsor wallets are going to be different this time. So I was thinking about this as an "update" more than "revert".

**Comment by bbenligiray** [comment]
I mean the check added in that PR will be checking for something that will never happen (after this issue is closed), no?
