### ISSUE TITLE
Use historical gas prices when RPC call for gas price fails

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#147]
See: https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1701327746032679

The exact details needs to be thought through. For example:
1. What defines a good enough set of historical prices?

**Comment by bbenligiray** [comment]
I'd say having a price from a fixed multiple (e.g. 10x) of the update interval is good enough. This would still need to be scaled & sanitized.

**Comment by bbenligiray** [comment]
Don't we collect a new gas price sample at every update interval?

**Comment by Siegrift** [comment]
> I'd say having a price from a fixed multiple (e.g. 10x) of the update interval is good enough.

From the above I understood, `gasPrice = 10 * updateInterval` which didn't make sense to me. I see that you meant something like "take the average of the gas prices from the last 10 update intervals and scale/sanitise that". I wonder about the benefits of doing this "mini-algorithm" compared to just taking the most freshly stored gas price.

**Comment by Siegrift** [comment]
Yeah, that makes sense.
