### ISSUE TITLE
Validate chain ID in the config

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#148]
It's possible that the chain ID in the Airseeker configuration to be wrong. This happened [here](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1701354756731899?thread_ts=1701354510.653479&cid=C05TQPT7PNJ). 

The chain ID is used for internal purposes and should match the chain ID of the target chain (the ID that providers use).

**Comment by Siegrift** [comment]
I would propose just doing a one-time config validation where we would call the RPC providers for chain IDs.

**Comment by bbenligiray** [comment]
What happens if they don't match though, WARN?

**Comment by Siegrift** [comment]
I wanted to error out. I think it's pretty serious if these don't match and most likely an human mistake.

**Comment by bbenligiray** [comment]
This is still only a log that discards the provider, right?

**Comment by Siegrift** [comment]
No. I mean, it will be a validation error during configuration parsing and Airseeker will exit immediately. What I am saying is that this configuration parsing is the first thing Airseeker does and is done only once (so it's just 1 RPC call).

**Comment by bbenligiray** [comment]
- This will result in the user thinking that they have an Airseeker running even though they don't, we don't want this. If the user is expected to listen to error logs, we can just log an error and discard the provider. If the user sees it and fixes the issue, good, if not, everything else still runs.
- It's not unheard of for an RPC provider to route the call to a node of the wrong blockchain, returning the wrong chain ID. They can even do it as an attack. Being able to take down the whole Airseeker this way is weird.

**Comment by Siegrift** [comment]
> This will result in the user thinking that they have an Airseeker running even though they don't, we don't want this. If the user is expected to listen to error logs, we can just log an error and discard the provider. If the user sees it and fixes the issue, good, if not, everything else still runs.

This happens anyway. Airseeker validates the configuration and if there is an error the container stops. You should always check whether the service runs after deploying it. Btw. what you mention won't happen, because when you deploy and the service errors out, AWS will try to restart it (maybe a few times) and then fail the deployment.

> It's not unheard of for an RPC provider to route the call to a node of the wrong blockchain, returning the wrong chain ID. They can even do it as an attack. Being able to take down the whole Airseeker this way is weird.

They would need to know exactly when you deploy Airseeker and the end result is deployment error which I consider a feature because it's a faulty provider which shouldn't be used.

**Comment by bbenligiray** [comment]
I'm optimizing Airseeker for a multiple-chain incident that happens in the middle of the night and the behavior you describe has the potential to be extremely detrimental in some cases (for example where an RPC provider is acting up across multiple chains).
If the chain ID is wrong, log a WARN and discard the provider. What I say is technically the user requirements.

**Comment by Siegrift** [comment]
Superceded by https://github.com/api3dao/airseeker-v2/issues/154
