### ISSUE TITLE
Multicall chain info with read calls, use tx count from the fetched block

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#154]
See: https://api3workspace.slack.com/archives/C05S589E7B4/p1701700197041599

**Comment by bbenligiray** [comment]
If we check the chain ID here too, https://github.com/api3dao/airseeker-v2/pull/153 becomes a bit redundant. I wasn't a fan anyway because we have seen providers switch chain IDs in the wild.

**Comment by Siegrift** [comment]
Also, make sure to log the tx counts per sponsor.

**Comment by Siegrift** [comment]
Blocked by https://github.com/api3dao/airseeker-v2/issues/163 and also we need to think about the exact logic how to detect out of sync providers (without breaking rollups and in general risking not doing legit feed updates).

**Comment by Siegrift** [comment]
* We want to prevent Airseeker doing an update based on outdated value (because provider is out of sync) causing draining of sponsor wallet.
* I couldn't think of a timestamp based check that would work for rollups (which only produce blocks when there are txs)
* Assume we use the nonce at the block of a static call. If there are other providers or a backup Airseeker doing updates with the same sponsor wallet, the transaction will be rejected because of a failing nonce and we will [log an error](https://github.com/api3dao/airseeker-v2/blob/4a0d274002fc3f55f06cbbb8732987b82478bae2/src/update-feeds-loops/submit-transactions.ts#L117). This also helps mitigate the issue of a provider returning correct (up to date) nonce, but out of date data.

Is there a case I am missing? I think that if we take the tx count at the block of the static call we end up with at most 1 "outdated" tx, but all subsequent will fail because of the nonce check.

**Comment by Siegrift** [comment]
We agreed on call to do what is mentioned in https://github.com/api3dao/airseeker-v2/issues/154#issuecomment-1862406549 which prevents draining the sponsor wallet.

**Comment by bbenligiray** [comment]
> the transaction will be rejected because of a failing nonce and we will [log an error](https://github.com/api3dao/airseeker-v2/blob/4a0d274002fc3f55f06cbbb8732987b82478bae2/src/update-feeds-loops/submit-transactions.ts#L117)

I think we should log an INFO here similar to when the transaction fails because the gas price has not been increased enough

**Comment by Siegrift** [comment]
I don't understand. Isn't logging an ERROR the same as INFO but with higher importance?

**Comment by bbenligiray** [comment]
I mean it doesn't necessarily mean that something has gone wrong so it's not good for it to pollute higher importance logs. Emit ERROR when you get the wrong chain ID all you want for example, that actually requires intervention from the user.
