### ISSUE TITLE
Consider `supported-chains` retired and `active` flags for `airseeker-admin` redeployments 

### ISSUE THREAD

**Issue by BTT21000** [api3dao/airseeker#187]
As shown in the latest [phase21-checklists v3.md](https://api3workspace.slack.com/archives/C01N6001YCE/p1707928017341029?thread_ts=1707927313.410289&cid=C01N6001YCE) checklists `Cint` and `Cret`, `airseeker-admin` should ensure airseeker-v2's deployments are updated after bumping to the new version of the `@api3/dapi-management` package. 

As such, `airseeker-admin` should treat the [supported-chains](https://github.com/api3dao/dapi-management/blob/main/data/supported-chains.json) flags (to be achieved with https://github.com/api3dao/dapi-management/issues/231) to enable those redeployments seamlessly.

**Comment by bbenligiray** [comment]
Currently done through mock-management
