### ISSUE TITLE
Fix handling of signed API URLs

### ISSUE THREAD

**Issue by bdrhn9** [api3dao/airseeker#190]
I encountered the following error when I deployed the airseeker-v2:

```
{"cause":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":80,"syscall":"connect"},"code":"ECONNREFUSED","dataFetcherCoordinatorId":"1708953860436","level":"warn","message":"connect ECONNREFUSED 127.0.0.1:80","ms":"+0ms","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:80\n    at AxiosError.from (/app/node_modules/.pnpm/axios@1.6.5/node_modules/axios/dist/node/axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (/app/node_modules/.pnpm/axios@1.6.5/node_modules/axios/dist/node/axios.cjs:3090:25)\n    at RedirectableRequest.emit (node:events:529:35)\n    at RedirectableRequest.emit (node:domain:489:12)\n    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.4_debug@4.3.4/node_modules/follow-redirects/index.js:37:24)\n    at ClientRequest.emit (node:events:517:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at Socket.socketErrorListener (node:_http_client:501:9)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2024-02-26T13:24:20.441Z"}
```

After investigating it, I found out that when [activeDataFeed](https://github.com/api3dao/contracts/blob/3276b9452a443d50c0f8fbe5a09343e66d7e37b5/contracts/api3-server-v1/AirseekerRegistry.sol#L360) function returns empty string for `signedApiUrls` (it's when `signedApiUrls` isn't set in the `AirseekerRegistry`), airseeker uses empty string as base URL and create a complete signed API URL (including airnode address) to make request, see [here](https://github.com/api3dao/airseeker-v2/blob/a99a98acb3a8235edb15aadf8c1274e77281c1a1/src/update-feeds-loops/update-feeds-loops.ts#L272). It creates URLs like `/airnodeAddress` and make request for them. 

Besides that, as I understand from [here](https://github.com/api3dao/airseeker-v2/blob/a99a98acb3a8235edb15aadf8c1274e77281c1a1/src/data-fetcher-loop/data-fetcher-loop.ts#L84), airseeker expects to see complete signed API URLs for each airnode in the config file like following:
```json
{
"signedApiUrls": [
"https://signed-api.stage.nodary.io/public/0x5791Fb78D4e37A9D0f0003199D1AE1A8C04C8d89", 
"https://signed-api.stage.nodary.io/public/0xc52EeA00154B4fF1EbbF8Ba39FDe37F1AC3B9Fd4", 
"https://signed-api.stage.nodary.io/public/0x8676eA8B6Ebe5b8FBbc25FF55192bADf39D7D61b"]
}
```
This setup complicates airseeker deployments because each time a new partner provider (airnode) is added, all airseekers must be redeployed. We only want to re-deploy airseekers when we add/remove chains.

My suggestion here:

- Behave signed-api URLs in configuration same with the ones on the contracts. So if we expect to read URL without airnode address in the contract, we should also expect to read URL without airnode address in the configuration file
- Detect empty URLs coming from the contract and don't include them into URLs to be called

**Comment by Siegrift** [comment]
> airseeker uses empty string as base URL and create a complete signed API URL (including airnode address) to make request

Mhh, are you sure? We are decoding the result [here](https://github.com/api3dao/airseeker-v2/blob/a99a98acb3a8235edb15aadf8c1274e77281c1a1/src/update-feeds-loops/contracts.ts#L127) so I'd expect it to be an empty array.

> Besides that, as I understand from [here](https://github.com/api3dao/airseeker-v2/blob/a99a98acb3a8235edb15aadf8c1274e77281c1a1/src/data-fetcher-loop/data-fetcher-loop.ts#L84), airseeker expects to see complete signed API URLs for each airnode in the config

Yeah, you are right. This is a bug - it should be the base URL and we should append the Airnode address as needed. However, there is related issue about the auth tokens. Each (full URL) Signed API can have different auth token which we won't have unless we specify it in Airseeker (and always redeploy). The only workaround I see is to change the authentication scheme (e.g. signature based by the Airseeker wallet which would also be compatible with Auctioneer).

**Comment by bdrhn9** [comment]
> Mhh, are you sure? We are decoding the result [here](https://github.com/api3dao/airseeker-v2/blob/a99a98acb3a8235edb15aadf8c1274e77281c1a1/src/update-feeds-loops/contracts.ts#L127) so I'd expect it to be an empty array.

Yes, it's array with size of beacons like = ['', '', '', '', '',..., '']

**Comment by bdrhn9** [comment]
> Yeah, you are right. This is a bug - it should be the base URL and we should append the Airnode address as needed. However, there is related issue about the auth tokens. Each (full URL) Signed API can have different auth token which we won't have unless we specify it in Airseeker (and always redeploy). The only workaround I see is to change the authentication scheme (e.g. signature based by the Airseeker wallet which would also be compatible with Auctioneer).

Shouldn't airseeker always utilize public endpoint of signed api?

**Comment by Siegrift** [comment]
> Yes, it's array with size of beacons like = ['', '', '', '', '',..., '']

Oh, I see 🤦 . I was too thoughtless when I looked at the function. The e2e tests I used always populate the array, so I didn't notice. Anyway, completely agree with filtering out empty URLs.

> Shouldn't airseeker always utilize public endpoint of signed api?

Actually, I am not sure. I remember discussing this a while ago, but forgot on the outcome. I asked in channel, just to be sure. If only public endpoint is used then we don't care about the auth token issue.

> Behave signed-api URLs in configuration same with the ones on the contracts. So if we expect to read URL without airnode address in the contract, we should also expect to read URL without airnode address in the configuration file

Provided the config scheme is good as is, then I agree with this as well.

**Comment by Siegrift** [comment]
FYI: You can disregard my point about auth tokens. [Airseeker will always use the public endpoint](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1709026856151499?thread_ts=1709013724.237969&cid=C05TQPT7PNJ).
