### ISSUE TITLE
Update entrypoint in Dockerfile

### ISSUE THREAD

**Issue by bdrhn9** [api3dao/airseeker#229]
As I figured out, adding the following line causes to compiling source files under `./dist/src/*` instead of `./dist/*`, that's why we need to update [entrypoint](https://github.com/api3dao/airseeker-v2/blob/aeea9d27eacdfe703d738efd194a1c8cb8daa94e/docker/Dockerfile#L26) of Dockerfile to be `/app/dist/src/index.js` 

https://github.com/api3dao/airseeker-v2/blob/2e8db23ab952e3cf21c19c307090c4ba529d00fe/tsconfig.json#L28

**Comment by Siegrift** [comment]
Actually this was because of https://github.com/api3dao/airseeker-v2/pull/216. We now read the version from package json, which caused a change in the folder structure of `dist` folder.

**Comment by Siegrift** [comment]
We set the working directory to `app` [here](https://github.com/api3dao/airseeker-v2/blob/aeea9d27eacdfe703d738efd194a1c8cb8daa94e/docker/Dockerfile#L4) so it should be just `dist/src/index.js` imo.
