### ISSUE TITLE
Respect the deviation reference

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker#230]
Update parameters includes a deviation reference. This should be respected while deciding if a deviation update needs to be made.

**Comment by Siegrift** [comment]
This was taken from the Airseeker v1 and I thought this hasn't changed. Can you clarify for me how the `deviationReference` should work? I tried to search for place where it is utilized/documented to find this.

**Comment by bbenligiray** [comment]
Like https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/api3-server-v1/extensions/BeaconSetUpdatesWithPsp.sol#L111
