### ISSUE TITLE
Support Airseeker running with a single sponsor wallet

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#253]
See: https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1706712947591099?thread_ts=1706521432.528779&cid=C05TQPT7PNJ

**Comment by bbenligiray** [comment]
https://github.com/api3dao/airseeker-v2/pull/296

**Comment by Siegrift** [comment]
Implemented in https://github.com/api3dao/airseeker-v2/pull/296
