### ISSUE TITLE
Make getting block number from RPC instead of contract configurable

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#273]
See: https://github.com/api3dao/airseeker-v2/pull/256

There are some chains ([arbitrum](https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/block-numbers-and-time#arbitrum-block-numbers)) for which `block.number` doesn't work as expected. 

This should be made configurable.

**Comment by bbenligiray** [comment]
With this, airseeker-admin (and the self-funded Nodary Airseeker, and whoever else will use Airseeker) will need to keep a list of chains for which it should enable this in the config, so operationally we will end up having a very similar thing + a more complex config. I think we should just maintain a list of chain IDs hardcoded in Airseeker and patch it as we need to add new chains, and abstract this away from the user.

**Comment by Siegrift** [comment]
Maybe this should be something in the @api3/chains repo? Aka some flag optional flag that all the packages can consume.

**Comment by bbenligiray** [comment]
Maybe the same applies to gas cost/gas limit stuff that @bdrhn9 has to handle on a chain by chain basis in logdata-miner. Maybe there should be script that one runs to determine these properties automatically @hiletmis .

**Comment by Siegrift** [comment]
So a script that determines this automatically in the chains repo? That way these properties can be autogenerated there.

Shall we create an issue in the chains repo for this?

**Comment by bbenligiray** [comment]
I created https://github.com/api3dao/chains/issues/264 and https://github.com/api3dao/chains/issues/265 but I think getting https://github.com/api3dao/chains/issues/264 right is important and we'll need some help from @bdrhn9 about that

**Comment by Siegrift** [comment]
I'm adding "blocked" label until this is implemented in chains.

**Comment by Siegrift** [comment]
See: https://github.com/api3dao/airseeker-v2/issues/314#issuecomment-2134717391

We are not always fetching the block number from the RPC.
