### ISSUE TITLE
Use `uuid` as coordinator ID

### ISSUE THREAD

**Issue by bdrhn9** [api3dao/airseeker#280]
Current timestamp is utilized as coordinator ID for both `dataFetcherCoordinatorId` and `updateFeedsCoordinatorId`. However timestamp isn't good choice to discriminate invoked functions especially there is bug related to race conditioning. That being said, because assigning coordinator ID is being done before staggering, coordinator IDs for same data feed from different RPC providers results in same.

**Comment by Siegrift** [comment]
> especially there is bug related to race conditioning

I don't see the case you're describing. One argument for using timestamp was ordering - you can easily see what coordinator loop started first. The problem with timestamp is that it's hard to visually distinguish it from other timestamp. That said, I see no disadvantage in using UUID and logging a timestamp at the start of the coordinator loop.

> coordinator IDs for same data feed from different RPC providers results in same.

I am not sure what you mean - the coordinator ID is different for each chain/provider combination.

**Comment by Siegrift** [comment]
Decided to stick with timestamp [here](https://github.com/api3dao/airseeker-v2/pull/292#discussion_r1593723714)

**Comment by Siegrift** [comment]
Changed decision in https://github.com/api3dao/airseeker-v2/pull/292#discussion_r1593739520
