### ISSUE TITLE
Fetch gas price natively

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#305]
See: https://api3workspace.slack.com/archives/C06R2JCFSS1/p1715585624116669?thread_ts=1715333508.842309&cid=C06R2JCFSS1

**Comment by Siegrift** [comment]
We discussed on the call to implement this now, but there was an idea to make sure sanitized gas price is higher than the base fee. Tracked in https://github.com/api3dao/airseeker-v2/issues/306

**Comment by Siegrift** [comment]
We discussed on call to only implement https://github.com/api3dao/airseeker-v2/issues/306

**Comment by bdrhn9** [comment]
Although the issue https://github.com/api3dao/airseeker-v2/issues/306 requires obtaining the base fee for blocks, my investigation of the underlying getFeeData function in ethers.js revealed that it does not directly return the block's base fee. Instead, it performs heuristic calculations using both the base fee and the maximum priority fee (`eth_maxPriorityFeePerGas`). Specifically, it returns a value computed as `2 * base fee + max priority fee`. You can see the implementation here: [ethers.js source code](https://github.com/ethers-io/ethers.js/blob/b1f67379342d9a1bb30c63e58cd6608db098084c/src.ts/providers/abstract-provider.ts#L938).

While it is theoretically possible to reverse this calculation to derive the base fee, it introduces several potential issues, such as handling cases where the maximum priority fee is null, and increases the risk of errors during the reverse calculation. Addition to that, we will still end up with making 3 calls (`eth_gasPrice`, `eth_getBlockByNumber`, `eth_maxPriorityFeePerGas`).

Therefore, it would be more efficient to fetch gas price using low-level RPC call.

**Comment by Siegrift** [comment]
Thanks for that. I agree.
