### ISSUE TITLE
Yahoo finances

### ISSUE THREAD

**Issue by djs1990** [api3dao/airseeker#328]

**Comment by bbenligiray** [comment]
You can set up an Airnode feed & signed API pair (https://github.com/api3dao/signed-api) that serves the data you want and use airseeker-v2 to maintain data feeds with these.

If you want to request an API3-managed dAPI that you can purchase subscriptions for on the [API3 Market](https://market.api3.org/), use this form https://api3dao.typeform.com/to/yT2Gt2fd

**Comment by djs1990** [comment]
Please help me to do soo
