### ISSUE TITLE
Implement `heartbeatIntervalModifier`

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker#330]
See https://github.com/api3dao/airseeker-v2/issues/80 and https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1696499772685759

The value can be positive or negative. The resulting heartbeat interval cannot be negative.

Not having it means the fallback Airseeker will frontrun the primary one 50% of the time for heartbeats.

**Comment by BTT21000** [comment]
As per this [thread](https://api3workspace.slack.com/archives/C075C5780HJ/p1718618707123359?thread_ts=1717759634.606679&cid=C075C5780HJ):

> Regarding scroll though it seems like the last update was 42h ago:
> https://scrollscan.com/address/0xC60A583B052C5c35190393ECCdcaB20A76cbF777

> that's most likely the reason that the sponsor wallet didn't execute the last heartbeat update. If we hadn't done the update, the timestamp on the market would be older and centurion would have raised a high priority alert.
