### ISSUE TITLE
Use node@20 in the Docker image

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#340]
Currently, we use v18, which will be EoL soon.

**Comment by Siegrift** [comment]
Security patches end in 10months https://endoflife.date/nodejs.

As a note, this is trivial to implement, but it needs to be tested for potential breakages.

**Comment by dcroote** [comment]
I can take this one, but would need some guidance on a suitable testing strategy.

**Comment by BTT21000** [comment]
Deployments to be done on testnets

**Comment by dcroote** [comment]
Wouldn't it also make sense to fully commit to node v20 if we're updating it in the Dockerfile? It would necessitate changes in in the Actions workflow and package.json:

https://github.com/api3dao/airseeker/blob/79d02d1d1a4ad5776844d04f6a31e963c0f49114/package.json#L7

@bdrhn9 ?

**Comment by bdrhn9** [comment]
> Wouldn't it also make sense to fully commit to node v20 if we're updating it in the Dockerfile? It would necessitate changes in in the Actions workflow and package.json:

Yes it would be 👍🏼
